# Cliente PPPoE Server
Vagrant.configure("2") do |config|
  config.vm.define "vagrant_cliente1" do |cliente|
    cliente.vm.box = "generic/ubuntu2204"
    cliente.vm.hostname = "vagrant_cliente1"
    # cliente.vm.network "private_network", ip: "192.168.56.101"
    cliente.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      # # Habilita aceleração gráfica para compatibilidade
      # vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
      # vb.customize ["modifyvm", :id, "--accelerate3d", "on"]

      vb.customize ["modifyvm", :id, "--nic2", "bridged"]
      vb.customize ["modifyvm", :id, "--bridgeadapter2", "tap-client"]
    end
    # Script para instalar XFCE + xrdp + ferramentas PPPoE
    cliente.vm.provision "shell", path: "scripts/rdp_cliente.sh"
    cliente.vm.network "forwarded_port", guest: 3389, host: 33890, id: "rdp"
  end
end