# Vagrant.configure("2") do |config|
#   config.vm.box = "bento/ubuntu-22.04"

#   # Cliente PPPoE Server
#   config.vm.define "cliente1" do |cli|
#     cli.vm.hostname = "cliente1"
#     cli.vm.provider "virtualbox" do |vb|
#       vb.gui = true
#       vb.name = "vagrant_cliente"
#       vb.memory = 2048
#       vb.cpus = 3
#       vb.name = "vagrant_cliente1"

#       # Habilita aceleração 3D e define controlador gráfico para VMSVGA
#       vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
#       vb.customize ["modifyvm", :id, "--accelerate3d", "on"]

#       vb.customize ["modifyvm", :id, "--nic2", "bridged"]
#       vb.customize ["modifyvm", :id, "--bridgeadapter2", "tap-client"]
#     end
#     cli.vm.provision "shell", path: "scripts/cliente1.sh"
#   end
# end

Vagrant.configure("2") do |config|
  config.vm.define "cliente1" do |cliente|
    cliente.vm.box = "generic/ubuntu2204"
    cliente.vm.hostname = "cliente1"
    # cliente.vm.network "private_network", ip: "192.168.56.101"
    cliente.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      # # Habilita aceleração gráfica para compatibilidade
      # vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
      # vb.customize ["modifyvm", :id, "--accelerate3d", "on"]

      vb.customize ["modifyvm", :id, "--nic2", "bridged"]
      vb.customize ["modifyvm", :id, "--bridgeadapter2", "tap-client"]
    end
    # Script para instalar XFCE + xrdp + ferramentas PPPoE
    cliente.vm.provision "shell", path: "scripts/gui_rdp_cliente.sh"
    # cliente.vm.provision "shell", path: "scripts/fix_network_manager.sh"
    cliente.vm.network "forwarded_port", guest: 3389, host: 33890, id: "rdp"
  end
end