Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  
  config.vm.define "bgp_internal" do |bgp1|
    bgp1.disksize.size = "20GB"
    bgp1.vm.hostname = 'bgp-internal'
    bgp1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "vagrant_bgp_internal"
    end
    bgp1.vm.network "private_network", ip: "192.168.33.10"
    bgp1.vm.provision "shell", path: "scripts/bgp_internal_provision.sh"
  end

  config.vm.define "bgp_external" do |bgp2|
    bgp2.disksize.size = "20GB"
    bgp2.vm.hostname = 'bgp-external'
    bgp2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "vagrant_bgp_external"
    end
    bgp2.vm.network "private_network", ip: "192.168.33.11"
    bgp2.vm.provision "shell", path: "scripts/bgp_external_provision.sh"
  end
  # # Configuração do Firewall
  # config.vm.define "firewall" do |fw|
  #   fw.vm.box = "bento/ubuntu-22.04"
  #   fw.disksize.size = "20GB"
  #   fw.vm.hostname = "firewall"
  #   fw.vm.provider "virtualbox" do |vb|
  #     vb.memory = "1024"
  #     vb.cpus = 2
  #     vb.name = "firewall"
  #   end
  #   fw.vm.network "private_network", ip: "192.168.100.1" # WAN (conectar ao BGP)
  #   fw.vm.network "private_network", ip: "192.168.100.2" # LAN (conectar ao Open vSwitch)
  #   fw.vm.provision "shell", path: "firewall.sh"
  # end
end
