Vagrant.configure("2") do |config|
  # Máquina virtual para o servidor web
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    web.disksize.size = "40GB"
    web.vm.network "private_network", ip: "192.168.56.110"
    web.vm.provision "shell", path: "initial-nfv-vms_setups.sh"
    web.vm.provision "shell", inline: "sudo apt-get install -y apache2"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  # Máquina virtual para o HAProxy
  config.vm.define "haproxy" do |haproxy|
    haproxy.vm.box = "ubuntu/bionic64"
    haproxy.disksize.size = "40GB"
    haproxy.vm.network "private_network", ip: "192.168.56.120"
    haproxy.vm.provision "shell", path: "initial-nfv-vms_setups.sh"
    haproxy.vm.provision "shell", inline: "sudo apt-get install -y haproxy"
    haproxy.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  # Máquina virtual para o Firewall
  config.vm.define "firewall" do |firewall|
    firewall.vm.box = "ubuntu/bionic64"
    firewall.disksize.size = "40GB"
    firewall.vm.network "private_network", ip: "192.168.56.130"
    firewall.vm.provision "shell", path: "initial-nfv-vms_setups.sh"
    firewall.vm.provision "shell", inline: "sudo apt-get install -y iptables"
    firewall.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end
end