Vagrant.configure("2") do |config|
  # Máquina virtual para o servidor web
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    web.disksize.size = "40GB"
    web.vm.network "private_network", ip: "192.168.56.110"
    web.vm.provision "shell", path: "web1-config.sh"
    # web.vm.provision "shell", path: "initial-nfv-vms_setups.sh"
    # web.vm.provision "shell", inline: "sudo apt-get install -y apache2"
    # web.vm.provision "shell", inline: "sudo ovs-vsctl add-br br0"
    # web.vm.provision "shell", inline: "sudo ovs-vsctl add-port br0 eth1"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  end

  config.vm.define "web2" do |web2|
    web2.vm.box = "ubuntu/bionic64"
    web2.disksize.size = "40GB"
    web2.vm.network "private_network", ip: "192.168.56.115"
    web2.vm.provision "shell", path: "web2-config.sh"
    # web2.vm.provision "shell", path: "initial-nfv-vms_setups.sh"
    # web2.vm.provision "shell", inline: "sudo apt-get install -y apache2"
    # web2.vm.provision "shell", inline: "sudo ovs-vsctl add-br br0"
    # web2.vm.provision "shell", inline: "sudo ovs-vsctl add-port br0 eth1"
    web2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  end

  # Máquina virtual para o HAProxy - balanceador de carga
  config.vm.define "haproxy" do |haproxy|
    haproxy.vm.box = "ubuntu/bionic64"
    haproxy.disksize.size = "40GB"
    haproxy.vm.network "private_network", ip: "192.168.56.120"
    haproxy.vm.provision "shell", path: "haproxy-config.sh"
    # haproxy.vm.provision "shell", path: "initial-nfv-vms_setups.sh"
    # haproxy.vm.provision "shell", inline: "sudo apt-get install -y haproxy"
    # haproxy.vm.provision "shell", inline: "sudo ovs-vsctl add-br br0"
    # haproxy.vm.provision "shell", inline: "sudo ovs-vsctl add-port br0 eth1"
    haproxy.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  end

  # Máquina virtual para o Firewall
  config.vm.define "firewall" do |firewall|
    firewall.vm.box = "ubuntu/bionic64"
    firewall.disksize.size = "40GB"
    firewall.vm.network "private_network", ip: "192.168.56.130"
    firewall.vm.provision "shell", path: "firewall-config.sh"
    # firewall.vm.provision "shell", path: "initial-nfv-vms_setups.sh"
    # firewall.vm.provision "shell", inline: "sudo apt-get install -y iptables"
    # firewall.vm.provision "shell", inline: "sudo ovs-vsctl add-br br0"
    # firewall.vm.provision "shell", inline: "sudo ovs-vsctl add-port br0 eth1"
    firewall.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  end
end